#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

setxkmap es &
feh --bg-fill /home/varssev/Images/background/bg1.jpg
picom --experimental-backends &
~/.config/polybar/launch.sh

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#b026ff
bspc config normal_border_color \#54fff1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
